#!/bin/sh

PLATFORM='linux/arm/v7,linux/arm64/v8,linux/amd64'
echo "${PLATFORM}"

IMAGE_DATE="$(date --rfc-3339=date)"
echo "${IMAGE_DATE}"

IMAGE_URL="https://gallery.ecr.aws/docker/library/debian"
echo "${IMAGE_URL}"

IMAGE_VERSION='unstable-slim
stable-slim'
echo "${IMAGE_VERSION}"

## build args
cat <<EOF > "${BUILD_FOLDER}/build-arg.env"
## generated by build-helper.sh

IMAGE_DATE=${IMAGE_DATE}
IMAGE_URL=${IMAGE_URL}
IMAGE_VERSION=${IMAGE_VERSION}

EOF

